const SAMPLE_API_RESPONSE_DATA = 'data';
const SAMPLE_API_RESPONSE_DATA_DATE = 'date';
const SAMPLE_API_RESPONSE_DATA_LOREM = 'lorem';
const SAMPLE_API_RESPONSE_DATA_IPSUM = 'ipsum';

const sampleApiTypes = {
  SAMPLE_API_RESPONSE_DATA,
  SAMPLE_API_RESPONSE_DATA_DATE,
  SAMPLE_API_RESPONSE_DATA_LOREM,
  SAMPLE_API_RESPONSE_DATA_IPSUM
};

export {
  sampleApiTypes as default,
  sampleApiTypes,
  SAMPLE_API_RESPONSE_DATA,
  SAMPLE_API_RESPONSE_DATA_DATE,
  SAMPLE_API_RESPONSE_DATA_LOREM,
  SAMPLE_API_RESPONSE_DATA_IPSUM
};
